tomcMatijaFilmRecenzije/filmRecenzije/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

tomcMatijaFilmRecenzije/main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home),
    path('signup/', views.signup_view),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='main:login'), name='logout'),
    path('film/', views.FilmView.as_view()),
    path('film/<int:movie_id>/', views.movie_detail, name='film_detalji'),
    path('recenzija/edit/<int:review_id>/', views.edit_review, name='edit_review'),
    path('recenzija/<int:review_id>/delete/', views.delete_review, name='delete_review'),
    path('recenzije/', views.recenzije)
]

tomcMatijaFilmRecenzije/main/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def str(self):
        return self.user.username

class Film(models.Model):
    nazivFilma = models.CharField(max_length=100)
    redateljFilma = models.CharField(max_length=100)
    godinaIzlaska = models.IntegerField()
    zanr = models.CharField(max_length=100)
    preporukeFilma = models.ManyToManyField('self', blank=True, symmetrical=False, related_name='preporuke')

    def __str__(self) -> str:
        return self.nazivFilma

    def Ocjena(self):
        avg_rating = self.recenzija_set.aggregate(models.Avg('ocjena'))['ocjena__avg']
        return round(avg_rating, 1) if avg_rating is not None else None

class Recenzija(models.Model):
    autorRecenzije = models.ForeignKey(User, on_delete=models.CASCADE)
    recenzija = models.TextField()
    ocjena = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.film.nazivFilma}/{self.autorRecenzije}"

tomcMatijaFilmRecenzije/main/forms.py
from django import forms
from .models import Recenzija

class RecenzijaForm(forms.ModelForm):
    class Meta:
        model = Recenzija
        fields = ['ocjena', 'recenzija']

tomcMatijaFilmRecenzije/main/views.py
from django.views.generic import *
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from .models import *
from .forms import RecenzijaForm

# Create your views here.

def home(request):
    return render(request,  'home.html')

def signup_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        if password != password2:
            context = {"message":"Lozinke se ne podudaraju"}
            return render(request, 'signup.html', context)

        if User.objects.filter(username=username).exists():
            context = {"message":"Korisničko ime već postoji"}
            return render(request, 'signup.html', context)

        if User.objects.filter(email=email).exists():
            context = {"message":"Email se več koristi"}
            return render(request, 'signup.html', context)

        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('/') 

    return render(request, 'signup.html')

def login_view(request):
    message = ""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            message = "Korisničko ime ili lozinka nisu ispravni"

    context={'message':message}
    return render(request, 'login.html', context)

class FilmView(ListView):
    model = Film
    context_object_name = 'filmovi'
    template_name = 'film.html'
    
def movie_detail(request, movie_id):
    movie = get_object_or_404(Film, id=movie_id)
    recenzije = Recenzija.objects.filter(film_id=movie_id)

    if request.method == 'POST':
        form = RecenzijaForm(request.POST)
        if form.is_valid():
            ocjena = form.cleaned_data['ocjena']
            recenzija_text = form.cleaned_data['recenzija']

            Recenzija.objects.create(
                autorRecenzije=request.user,
                ocjena=ocjena,
                recenzija=recenzija_text,
                film=movie
            )

            return redirect('main:film_detalji', movie_id=movie.id)
    else:
        form = RecenzijaForm()

    return render(request, 'film_detalji.html', {'movie': movie, 'recenzije': recenzije, 'form': form})


def edit_review(request, review_id):
    review = get_object_or_404(Recenzija, id=review_id)

    if request.method == 'POST':
        form = RecenzijaForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    else:
        form = RecenzijaForm(instance=review)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

def delete_review(request, review_id):
    review = get_object_or_404(Recenzija, id=review_id)

    if request.method == 'POST':
        review.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

def recenzije(request):
    recenzije = Recenzija.objects.filter(autorRecenzije=request.user)

    if request.method == 'POST':
        form = RecenzijaForm(request.POST)
        if form.is_valid():
            ocjena = form.cleaned_data['ocjena']
            recenzija_text = form.cleaned_data['recenzija']

            Recenzija.objects.create(
                autorRecenzije=request.user,
                ocjena=ocjena,
                recenzija=recenzija_text,
                film=movie
            )

            return render(request, 'recenzije.html', {'recenzije': recenzije, 'form': form})
    else:
        form = RecenzijaForm()

    return render(request, 'recenzije.html', {'recenzije': recenzije, 'form': form})

tomcMatijaFilmRecenzije/main/templates/film.html
{% extends 'home.html' %}

{% block content %}
{% for film in filmovi%}
<div>
    <h4><a href="{% url 'main:film_detalji' film.id %}">{{ film.nazivFilma }}</a></h4>
    <p>Redatelj: {{ film.redateljFilma }}</p>
    <p>Godina izlaska: {{ film.godinaIzlaska }}</p>
    <p>Žanr: {{ film.zanr }}</p>
    <p>Ocjena: {{ film.Ocjena|default:0 }}</p>
</div>
{% endfor %}
{% endblock %}

tomcMatijaFilmRecenzije/main/templates/film_detalji.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{{ movie.nazivFilma }}</title>
</head>

<body>
    <h3><a href="/film">Nazad na početnu</a></h3>
    <h1>{{ movie.nazivFilma }}</h1>
    <p>Redatelj: {{ movie.redateljFilma }}</p>
    <p>Godina izlaska: {{ movie.godinaIzlaska }}</p>
    <p>Žanr: {{ movie.zanr }}</p>

    <h3>Preporuke</h3>
    <ul>
        {% for preporuka in movie.preporukeFilma.all %}
            <li><a href="{% url 'main:film_detalji' preporuka.id %}">{{ preporuka.nazivFilma }} ({{ preporuka.godinaIzlaska }})</a></li>
        {% empty %}
            <li>Nema preporuka.</li>
        {% endfor %}
    </ul>

    <h3>Kreiraj novu recenziju</h3>
    <form method="post" action="{% url 'main:film_detalji' movie.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Spremi</button>
    </form>

    <h3>Recenzije</h3>
    {% for recenzija in recenzije %}
    <div>
        <p>Autor: {{ recenzija.autorRecenzije }}</p>
        <p>Ocjena: {{ recenzija.ocjena }}</p>
        <p>Recenzija: {{ recenzija.recenzija }}</p>
        {% if user.is_authenticated and recenzija.autorRecenzije == user %}
            <form method="post" action="{% url 'main:edit_review' recenzija.id %}" style="display: none;">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Spremi promjene</button>
            </form>
            <button class="edit-button" data-review-id="{{ recenzija.id }}">Uredi</button>
            
            <form id="delete-review-form-{{ recenzija.id }}" method="post" action="{% url 'main:delete_review' recenzija.id %}" style="display: none;">
                {% csrf_token %}
                <button type="submit">Izbriši</button>
            </form>
            <button class="delete-button" data-review-id="{{ recenzija.id }}">Izbriši</button>
        {% endif %}
    </div>
    {% endfor %}
</body>

<script>
    document.querySelectorAll('.edit-button').forEach(function(button) {
        button.addEventListener('click', function() {
            var reviewId = this.getAttribute('data-review-id');
            var form = document.querySelector('form[action="{% url "main:edit_review" 0 %}"]'.replace('0', reviewId));
            form.style.display = form.style.display === 'none' ? 'block' : 'none';
        });
    });

    document.querySelectorAll('.delete-button').forEach(function(button) {
        button.addEventListener('click', function() {
            var reviewId = this.getAttribute('data-review-id');
            var confirmation = confirm("Jeste li sigurni da želite izbrisat recenziju?");
            if (confirmation) {
                document.getElementById('delete-review-form-' + reviewId).submit();
            }
        });
    });
</script>

</html>

tomcMatijaFilmRecenzije/main/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
</head>

<body>
    <h1><a href="/">Početna</a></h1>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            {% if not user.is_authenticated %}
                <li><a href="/signup">Sign up</a></li>
                <li><a href="/login">Log in</a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li><a href="/film">Film</a></li>
                <li><a href="/recenzije">Moje recenzije</a></li>   
            {% endif %}
        </ul>
        {% endblock %}
    </div>

    {% if user.is_authenticated %}
        <h2>Dobrodošli, {{ user.username }}!</h2>
        <li><a href="{% url 'main:logout' %}">Logout</a></li>
    {% endif %}

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

tomcMatijaFilmRecenzije/main/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body align="center">
    <h1 align="left"><a href="/">Početna</a></h1>
    <h2>Log in</h2>
    <form method="post">
        {% csrf_token %}
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}
        <label for="username">Korisničko ime:</label><br>
        <input type="text" id="username" name="username" required><br>
        <label for="password">Lozinka:</label><br>
        <input type="password" id="password" name="password" required><br><br>
        <button type="submit">Log in</button>
    </form>
    <a href="/signup">Sign up</a>
</body>
</html>

tomcMatijaFilmRecenzije/main/templates/recenzije.html
{% extends 'home.html' %}

{% block content %}
<h2>Moje recenzije</h2>
{% for recenzija in recenzije %}
    <div>
        <h4><a href="{% url 'main:film_detalji' recenzija.film.id %}">{{ recenzija.film.nazivFilma }}</h4></a>
        <p>Autor: {{ recenzija.autorRecenzije }}</p>
        <p>Ocjena: {{ recenzija.ocjena }}</p>
        <p>Recenzija: {{ recenzija.recenzija }}</p>
        <form method="post" action="{% url 'main:edit_review' recenzija.id %}" style="display: none;">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Spremi promjene</button>
        </form>
        <button class="edit-button" data-review-id="{{ recenzija.id }}">Uredi</button>
        
        <form id="delete-review-form-{{ recenzija.id }}" method="post" action="{% url 'main:delete_review' recenzija.id %}" style="display: none;">
            {% csrf_token %}
            <button type="submit">Izbriši</button>
        </form>
        <button class="delete-button" data-review-id="{{ recenzija.id }}">Izbriši</button>
    </div>
{% endfor %}

<script>
    document.querySelectorAll('.edit-button').forEach(function(button) {
        button.addEventListener('click', function() {
            var reviewId = this.getAttribute('data-review-id');
            var form = document.querySelector('form[action="{% url "main:edit_review" 0 %}"]'.replace('0', reviewId));
            form.style.display = form.style.display === 'none' ? 'block' : 'none';
        });
    });

    document.querySelectorAll('.delete-button').forEach(function(button) {
        button.addEventListener('click', function() {
            var reviewId = this.getAttribute('data-review-id');
            var confirmation = confirm("Jeste li sigurni da želite izbrisat recenziju?");
            if (confirmation) {
                document.getElementById('delete-review-form-' + reviewId).submit();
            }
        });
    });
</script>

{% endblock %}

tomcMatijaFilmRecenzije/main/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body align="center">
    <h1 align="left"><a href="/">Početna</a></h1>
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}
        <label for="username">Korisniško ime:</label><br>
        <input type="text" id="username" name="username" required><br>
        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email" required><br>
        <label for="password">Lozinka:</label><br>
        <input type="password" id="password" name="password" required><br>
        <label for="password2">Potvrdite lozinku:</label><br>
        <input type="password" id="password2" name="password2" required><br><br>
        <button type="submit">Sign Up</button> 
    </form>
    <a href="/login">Log in</a>
</body>
</html>